In [1]:
import pandas as pd

In [2]:
pwd

'C:\\Users\\James B\\repos\\lambda_school_ds\\labs\\juxta-city-data-ds\\findurcity\\notebooks'

In [3]:
cd ..

C:\Users\James B\repos\lambda_school_ds\labs\juxta-city-data-ds\findurcity

In [4]:
cd src/datasets/

C:\Users\James B\repos\lambda_school_ds\labs\juxta-city-data-ds\findurcity\src\datasets

In [5]:
df = pd.read_excel('ctyfactbook2019.xlsx')

In [6]:
df.head()

,"Air Quality Statistics by County, 2019",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Note: The values shown are the highest among t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),PM2.5 Wtd AM (µg/m3),PM2.5 24-hr (µg/m3),SO2 1-hr (ppb)
2,Alabama,Baldwin County,01003,182265,ND,ND,ND,ND,0.063,ND,7.5,15,ND
3,Alabama,Clay County,01027,13932,ND,ND,ND,ND,ND,ND,7.4,15,ND
4,Alabama,Colbert County,01033,54428,ND,ND,ND,ND,0.056,ND,IN,IN,ND

In [7]:
df.columns = df.iloc[1]

In [8]:
df = df.drop([0, 1]).reset_index(drop=True)

In [9]:
df.columns.name = None

In [10]:
df.head()

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),PM2.5 Wtd AM (µg/m3),PM2.5 24-hr (µg/m3),SO2 1-hr (ppb)
0,Alabama,Baldwin County,01003,182265,ND,ND,ND,ND,0.063,ND,7.5,15,ND
1,Alabama,Clay County,01027,13932,ND,ND,ND,ND,ND,ND,7.4,15,ND
2,Alabama,Colbert County,01033,54428,ND,ND,ND,ND,0.056,ND,IN,IN,ND
3,Alabama,DeKalb County,01049,71109,ND,ND,ND,ND,0.062,ND,IN,IN,ND
4,Alabama,Elmore County,01051,79303,ND,ND,ND,ND,0.059,ND,ND,ND,ND

In [11]:
df.tail(20)

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),PM2.5 Wtd AM (µg/m3),PM2.5 24-hr (µg/m3),SO2 1-hr (ppb)
1140,Puerto Rico,"Humacao Municipio, Puerto Rico",72069,58466,ND,ND,ND,ND,ND,ND,IN,IN,ND
1141,Puerto Rico,"Lares Municipio, Puerto Rico",72081,30753,ND,ND,ND,ND,ND,ND,IN,IN,ND
1142,Puerto Rico,"Mayagüez Municipio, Puerto Rico",72097,89080,ND,ND,ND,ND,0.014,ND,IN,IN,ND
1143,Puerto Rico,"Ponce Municipio, Puerto Rico",72113,166327,1,ND,ND,ND,ND,94,6.3,17,ND
1144,Puerto Rico,"San Juan Municipio, Puerto Rico",72127,395326,3,ND,ND,ND,ND,ND,IN,IN,ND
1145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1146,CO - Second maximum non-overlapping 8-hour co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1147,Pb - Maximum rolling 3 month average (applic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1148,NO2 (AM) - Arithmetic mean concentration (ap...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1149,NO2 (1-hr) - 98th percentile daily maximum ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1150,O3 - Fourth daily maximum 8-hour concentrati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1151,PM10 - Second maximum 24-hour concentration ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1152,PM2.5 (Wtd AM) - Weighted annual mean conce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1153,PM2.5 (24-hr) - 98th percentile 24-hour con...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154,SO2 - 99th percentile daily maximum 1-hour c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1155,ND - No Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1156,IN - Insufficient data to calculate summary ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1157,µg/m3 - micrograms per cubic meter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1158,ppm - parts per million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1159,ppb - parts per billion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
legend = df['State'].tail(14).to_list()

In [13]:
legend

['CO -  Second maximum non-overlapping 8-hour concentration (applicable NAAQS is 9 ppm)',
 'Pb  -  Maximum rolling 3 month average (applicable NAAQS is 0.15 µg/m3)',
 'NO2  (AM) -  Arithmetic mean concentration (applicable NAAQS is 53 ppb)',
 'NO2  (1-hr)  -  98th percentile daily maximum 1-hour concentration (applicable NAAQS is 100 ppb)',
 'O3  -  Fourth daily maximum 8-hour concentration (applicable NAAQS is 0.070 ppm)',
 'PM10  -  Second maximum 24-hour concentration (applicable NAAQS is 150 µg/m3)',
 'PM2.5  (Wtd AM)  -  Weighted annual mean concentration (applicable NAAQS is 12 µg/m3)',
 'PM2.5  (24-hr)  -  98th percentile 24-hour concentration (applicable NAAQS is 35 µg/m3)',
 'SO2  -  99th percentile daily maximum 1-hour concentration (applicable NAAQS is 75 ppb)',
 'ND  -  No Data',
 'IN  -  Insufficient data to calculate summary statistic',
 'µg/m3  -  micrograms per cubic meter',
 'ppm  -  parts per million',
 'ppb  -  parts per billion']

In [14]:
air_quality = df[:-15]

In [15]:
air_quality.head()

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),PM2.5 Wtd AM (µg/m3),PM2.5 24-hr (µg/m3),SO2 1-hr (ppb)
0,Alabama,Baldwin County,01003,182265,ND,ND,ND,ND,0.063,ND,7.5,15,ND
1,Alabama,Clay County,01027,13932,ND,ND,ND,ND,ND,ND,7.4,15,ND
2,Alabama,Colbert County,01033,54428,ND,ND,ND,ND,0.056,ND,IN,IN,ND
3,Alabama,DeKalb County,01049,71109,ND,ND,ND,ND,0.062,ND,IN,IN,ND
4,Alabama,Elmore County,01051,79303,ND,ND,ND,ND,0.059,ND,ND,ND,ND

In [19]:
names = []

for col in air_quality.columns:
    names.append(' '.join(col.split()))

col_names = {}
for old_col, new_col in zip(air_quality.columns, names):
    col_names.update({old_col: new_col})
print(col_names)

{'State': 'State', 'County': 'County', 'County FIPS Code': 'County FIPS Code', '2010 Population': '2010 Population', 'CO          8-hr (ppm)': 'CO 8-hr (ppm)', 'Pb           3-mo (µg/m3)': 'Pb 3-mo (µg/m3)', 'NO2         AM (ppb)': 'NO2 AM (ppb)', 'NO2          1-hr (ppb)': 'NO2 1-hr (ppb)', 'O3            8-hr (ppm)': 'O3 8-hr (ppm)', 'PM10        24-hr (µg/m3) ': 'PM10 24-hr (µg/m3)', 'PM2.5     Wtd AM (µg/m3) ': 'PM2.5 Wtd AM (µg/m3)', 'PM2.5     24-hr (µg/m3) ': 'PM2.5 24-hr (µg/m3)', 'SO2         1-hr (ppb)': 'SO2 1-hr (ppb)'}

In [22]:
aq = air_quality.rename(col_names, axis='columns')

In [23]:
# df2 = aq[(aq['CO 8-hr (ppm)'] != 'ND') & (aq['CO 8-hr (ppm)'] != 'IN')]

In [24]:
# df2['CO'] = df2['CO 8-hr (ppm)'].astype(int)

C:\Users\James B\Anaconda3\envs\Juxta\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
# df2['CO'].value_counts()

1    107
2     36
0     19
3      6
Name: CO, dtype: int64

In [26]:
# df2.head()

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),PM2.5 Wtd AM (µg/m3),PM2.5 24-hr (µg/m3),SO2 1-hr (ppb),CO
8,Alabama,Jefferson County,01073,658466,1,ND,12,50,0.074,106,10.4,21,41,1
20,Alaska,Anchorage Municipality,02020,291826,2,ND,ND,ND,ND,98,8.2,42,ND,2
23,Alaska,Fairbanks North Star Borough,02090,97581,2,ND,IN,IN,0.047,200,15.5,78,30,2
34,Arizona,Maricopa County,04013,3817117,2,0.05,25,52,0.076,183,8.4,23,5,2
37,Arizona,Pima County,04019,980263,1,ND,7,30,0.065,139,3.8,9,1,1

In [54]:
new_aq = aq.replace({'ND': 0, 'IN': 0})

In [55]:
new_aq.dtypes

State                    object
County                   object
County FIPS Code         object
2010 Population           int64
CO 8-hr (ppm)             int64
Pb 3-mo (µg/m3)         float64
NO2 AM (ppb)              int64
NO2 1-hr (ppb)            int64
O3 8-hr (ppm)           float64
PM10 24-hr (µg/m3)        int64
PM2.5 Wtd AM (µg/m3)    float64
PM2.5 24-hr (µg/m3)       int64
SO2 1-hr (ppb)            int64
dtype: object

In [38]:
new_aq.head()

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (µg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (µg/m3),PM2.5 Wtd AM (µg/m3),PM2.5 24-hr (µg/m3),SO2 1-hr (ppb)
0,Alabama,Baldwin County,01003,182265,0,0.0,0,0,0.063,0,7.5,15,0
1,Alabama,Clay County,01027,13932,0,0.0,0,0,0.000,0,7.4,15,0
2,Alabama,Colbert County,01033,54428,0,0.0,0,0,0.056,0,0.0,0,0
3,Alabama,DeKalb County,01049,71109,0,0.0,0,0,0.062,0,0.0,0,0
4,Alabama,Elmore County,01051,79303,0,0.0,0,0,0.059,0,0.0,0,0

In [62]:
# Convert to correct units (multiplier dependent on Molecular Weight (M) of molecule)
new_aq['NO2 1-hr'] = new_aq['NO2 1-hr (ppb)'].apply(lambda x: x * 1.88)  # ug/m3
new_aq['SO2 1-hr'] = new_aq['SO2 1-hr (ppb)'].apply(lambda x: x * 2.62)  # ug/m3
new_aq['CO 8-hr'] = new_aq['CO 8-hr (ppm)'].apply(lambda x: 0.0409 * x * 28.01)  # mg/m3 (M = 28.01)
new_aq['O3 8-hr'] = new_aq['O3 8-hr (ppm)'].apply(lambda x: (0.0409 * x * 48) * 1000)  # ug/m3 (M = 48)
new_aq['24-hr PM10'] = new_aq['PM10 24-hr (µg/m3)']  # PM = Particulate Matter

final_aq = new_aq[['State', 'County', 'County FIPS Code', '2010 Population',
                   'CO 8-hr', 'O3 8-hr', 'NO2 1-hr', 'SO2 1-hr', '24-hr PM10'
                  ]]

In [72]:
final_aq.describe(exclude='object')

,2010 Population,CO 8-hr,O3 8-hr,NO2 1-hr,SO2 1-hr,24-hr PM10
count,1.145000e+03,1145.000000,1145.000000,1145.000000,1145.000000,1145.000000
mean,2.252326e+05,0.197105,83.466005,12.278288,13.278480,22.096070
std,4.916717e+05,0.557690,58.819298,28.465367,53.447643,113.371934
min,7.830000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.314800e+04,0.000000,0.000000,0.000000,0.000000,0.000000
50%,8.784100e+04,0.000000,115.828800,0.000000,0.000000,0.000000
75%,2.112260e+05,0.000000,125.644800,0.000000,2.620000,26.000000
max,9.818605e+06,3.436827,208.099200,156.040000,1121.360000,3427.000000

In [76]:
co_psi = []
for ob in final_aq['CO 8-hr']:
    if ob <= 5:
        co_psi.append('Good')
    elif (ob > 5) and (ob <= 10):
        co_psi.append('Moderate')
    elif (ob > 10) and (ob <= 17):
        co_psi.append('Unhealthy')
    elif (ob > 17) and (ob <= 34):
        co_psi.append('Very Unhealthy')
    else:
        co_psi.append('Hazardous')
set(co_psi)

{'Good'}

In [77]:
o3_psi = []
for ob in final_aq['O3 8-hr']:
    if ob <= 119:
        o3_psi.append('Good')
    elif (ob > 119) and (ob <= 157):
        o3_psi.append('Moderate')
    elif (ob > 157) and (ob <= 235):
        o3_psi.append('Unhealthy')
    elif (ob > 235) and (ob <= 785):
        o3_psi.append('Very Unhealthy')
    else:
        o3_psi.append('Hazardous')
set(o3_psi)

{'Good', 'Moderate', 'Unhealthy'}

In [78]:
no2_psi = []
for ob in final_aq['NO2 1-hr']:
    if ob < 1130:
        no2_psi.append('Good')
#     elif (ob > 119) and (ob <= 157):
#         no2_psi.append('Moderate')
    elif (ob > 1130) and (ob <= 2260):
        no2_psi.append('Unhealthy')
    elif (ob > 2260) and (ob <= 2260):
        no2_psi.append('Very Unhealthy')
    else:
        no2_psi.append('Hazardous')
set(no2_psi)

{'Good'}

In [79]:
so2_psi = []
for ob in final_aq['SO2 1-hr']:
    if ob <= 80:
        so2_psi.append('Good')
    elif (ob > 80) and (ob <= 365):
        so2_psi.append('Moderate')
    elif (ob > 365) and (ob <= 800):
        so2_psi.append('Unhealthy')
    elif (ob > 800) and (ob <= 1600):
        so2_psi.append('Very Unhealthy')
    else:
        so2_psi.append('Hazardous')
set(so2_psi)

{'Good', 'Moderate', 'Unhealthy', 'Very Unhealthy'}

In [80]:
pm10_psi = []
for ob in final_aq['24-hr PM10']:
    if ob <= 50:
        pm10_psi.append('Good')
    elif (ob > 50) and (ob <= 150):
        pm10_psi.append('Moderate')
    elif (ob > 150) and (ob <= 350):
        pm10_psi.append('Unhealthy')
    elif (ob > 350) and (ob <= 240):
        pm10_psi.append('Very Unhealthy')
    else:
        pm10_psi.append('Hazardous')
set(pm10_psi)

{'Good', 'Hazardous', 'Moderate', 'Unhealthy'}

In [83]:
final_aq['CO_category'] = co_psi
final_aq['O3_category'] = o3_psi
final_aq['NO2_category'] = no2_psi
final_aq['SO2_category'] = so2_psi
final_aq['PM10_category'] = pm10_psi

final_aq.head()

C:\Users\James B\Anaconda3\envs\Juxta\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\James B\Anaconda3\envs\Juxta\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\James B\Anaconda3\envs\Juxta\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\James B\Anaconda3\envs\Juxta\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\James B\Anaconda3\envs\Juxta\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,State,County,County FIPS Code,2010 Population,CO 8-hr,O3 8-hr,NO2 1-hr,SO2 1-hr,24-hr PM10,CO_category,O3_category,NO2_category,SO2_category,PM10_category
0,Alabama,Baldwin County,01003,182265,0.0,123.6816,0.0,0.0,0,Good,Moderate,Good,Good,Good
1,Alabama,Clay County,01027,13932,0.0,0.0000,0.0,0.0,0,Good,Good,Good,Good,Good
2,Alabama,Colbert County,01033,54428,0.0,109.9392,0.0,0.0,0,Good,Good,Good,Good,Good
3,Alabama,DeKalb County,01049,71109,0.0,121.7184,0.0,0.0,0,Good,Moderate,Good,Good,Good
4,Alabama,Elmore County,01051,79303,0.0,115.8288,0.0,0.0,0,Good,Good,Good,Good,Good

In [90]:
# final_aq.to_csv('aq_cleaned.csv', index=False)

In [100]:
for col in final_aq.columns[-5:]:
    print(final_aq[col].value_counts())
    print('----------------------------------')

Good    1145
Name: CO_category, dtype: int64
----------------------------------
Good         650
Moderate     480
Unhealthy     15
Name: O3_category, dtype: int64
----------------------------------
Good    1145
Name: NO2_category, dtype: int64
----------------------------------
Good              1089
Moderate            52
Unhealthy            3
Very Unhealthy       1
Name: SO2_category, dtype: int64
----------------------------------
Good         994
Moderate     129
Unhealthy     16
Hazardous      6
Name: PM10_category, dtype: int64
----------------------------------